lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

Gem::Specification.new do |spec|
  spec.name          = "fluent-plugin-docker-journald-concat"
  spec.version       = "0.1.1"
  spec.authors       = ["Oleksandr Kushchenko"]
  spec.email         = ["gearok@gmail.com"]

  spec.summary       = "Fluentd Filter plugin to concatenate partial log messages generated by Docker daemon with Journald logging driver"
  spec.description   = "Fluentd Filter plugin to concatenate partial log messages generated by Docker daemon with Journald logging driver"
  spec.homepage      = "https://github.com/okushchenko/fluent-plugin-docker-journald-concat"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").reject {|f| f.match(%r{^(test|spec|features)/}) }
  spec.require_paths = ["lib"]

  spec.add_runtime_dependency "fluentd", "~> 0.14"
  spec.add_development_dependency "bundler", "~> 1.11"
  spec.add_development_dependency "rake", "~> 12.0"
  spec.add_development_dependency "test-unit", "~> 3.1"
  spec.add_development_dependency "test-unit-rr", "~> 1.0"
end
